Changes and improvements for performance and more maintenable code.
OP-TED/eforms-notice-viewer pull request #49
Opened 2023-04-19 07:25 UTC by meletev

2023-04-19 09:40 UTC, bertrand-lorentz requested changes
With this change, the unit tests in NoticeViewerTest now all fail on my (Windows) laptop.
I see the unit tests are OK in the GitHub action, and looking at the files for those tests, it seems there is a difference in line endings (CRLF versus LF).

Before this PR, the files were not compared.
I don't think doing an exact comparison is needed or useful: any difference would be mostly caused by a change in the EFX toolkit (so not in the scope of unit tests for this project).
The unit tests are there to check that there is XSL or HTML generated, so some simple sanity check would be enough.

2023-04-19 09:54 UTC, rouschr approved these changes
Looks OK but see my comments.

2023-04-19 09:54 UTC, rouschr commented on src/main/java/eu/europa/ted/eforms/viewer/generator/HtmlGenerator.java
> +  private Charset charset;
Could be final.

2023-04-19 09:54 UTC, rouschr commented on src/main/java/eu/europa/ted/eforms/viewer/generator/HtmlGenerator.java
> +  private boolean profileXslt;
Could be final.

2023-04-20 07:59 UTC, meletev commented on src/main/java/eu/europa/ted/eforms/viewer/generator/HtmlGenerator.java
> +  private Charset charset;
Done

2023-04-20 07:59 UTC, meletev commented on src/main/java/eu/europa/ted/eforms/viewer/generator/HtmlGenerator.java
> +  private boolean profileXslt;
Done

2023-04-20 08:06 UTC, meletev commented
The usage of expected results has been reverted.
As explained by Bertrand, it might be hard to maintain and it also has newline issues on Windows, which can be re-introduced even if fixed now.

2023-04-20 08:08 UTC, rouschr approved these changes

2023-04-21 15:18 UTC, rousso submitted a review, later dismissed

2023-04-23 21:28 UTC, rousso approved these changes

2023-04-23 21:38 UTC, merged