[fix] add qualifier, update ANTLR dependency
OP-TED/eforms-notice-viewer pull request #90
Opened 2024-04-12 10:03 UTC by papacst

2024-04-15 08:49 UTC, bertrand-lorentz requested changes

2024-04-15 08:49 UTC, bertrand-lorentz commented on src/main/java/eu/europa/ted/eforms/viewer/DependencyFactory.java
>        return ComponentFactory.getScriptGenerator(sdkVersion, options);
For correctness, it would be better to pass along the "qualifier" parameter:
`return ComponentFactory.getScriptGenerator(sdkVersion, qualifier, options);`

It does not make a difference currently, as the notice viewer does use any component with qualifiers, but it might in the future.

The same comment applies to the other 2 methods that call `ComponentFactory` methods.

2024-04-17 14:02 UTC, papacst commented on src/main/java/eu/europa/ted/eforms/viewer/DependencyFactory.java
>        return ComponentFactory.getScriptGenerator(sdkVersion, options);
fixed

2024-04-18 09:20 UTC, bertrand-lorentz commented on src/main/java/eu/europa/ted/eforms/viewer/DependencyFactory.java
>        return ComponentFactory.getScriptGenerator(sdkVersion, options);
Looks good, thanks.

2024-04-19 07:00 UTC, merged